### ISSUE TITLE
Auto save for switch palace not working after changing the level

### ISSUE THREAD

**Issue by exedriver** [romhackraces/baserom#132]
Hi guys,
I've found another problem, which seems to be related somehow with the baserom - or I'm doing something wrong. At my hack (and also in a fresh copy of the baserom), the auto save prompt doesn't open after I beat a switch palace - no matter if I use the an original switch palaces entry level or a custom one (which I want).

Steps to reproduce:
- Add door in level 106 (first level on the right) with entrance to 9C (green switch palace)
- Overworld -> Change Special Message Level -> Switch Green Switch Palace Level from 8 to 106
- Overworld -> Change No-Auto-Move Level -> Switch Level #2 to 106
- Check Overworld -> Extra Options -> Bring up a save prompt when the player passes a castle, .,.. , Switch Palace,... is checked (is checked by default)

If I now start level 106, go through the door, press the green switch palace button, the message box is showing the green outlines from the green switch blocks, the green switch animation is triggered after returning to the overworld, but no save prompt is shown. Same happens if I leave everything by default, just move the mario sprite to the green switch level on the main overworld and clear level 8 (default entry for the green switch palace).

Any idea what creates this issue? The retry system maybe?

Any tip is very welcome. Thank you very much for your help :)

**Comment by AmperSam-git** [comment]
Well you may feel silly but it's just a thing you can check in the level tile properties:

![image](https://github.com/romhackraces/baserom/assets/81581391/de104ddf-8bef-42b0-91d0-205f0b3f1fb6)

**Comment by exedriver** [comment]
Hmm you're right - in the clean baserom, this will make the save prompt appear. 
In my hack sadly that doesn't work, so I guess there is an incompability with other patches or whatever :(

**Comment by exedriver** [comment]
> Hmm you're right - in the clean baserom, this will make the save prompt appear. In my hack sadly that doesn't work, so I guess there is an incompability with other patches or whatever :(

UPDATE: FOUND THE ISSUE!

You must have set a base event in the main level for the save prompt to appear! As I have no custom animation after beating the switch palace, I've had set this to "No Event" - but then no save prompt triggers. Now I've set an unused event and it works :)
