### ISSUE TITLE
`teleport_direct` breaks in exlevels

### ISSUE THREAD

**Issue by Underrout** [romhackraces/baserom#152]
`tools/gps/routines/teleport_direct.asm` does *not* work correctly in whatever those non-standard screen layout levels are called that were added in LM 3.00 cause you're supposed to call `$03BCDC` in LM 3.00+ to figure out the screen number the player is on rather than using the old method used in that file.

**Comment by AmperSam-git** [comment]
Yeah this is taken from a Doors resource for the sake of easy teleport. I'll probably rewrite the teleport block for the next release.
