### ISSUE TITLE
remove shortcut for lunar helper

### ISSUE THREAD

**Issue by Underrout** [romhackraces/baserom#74]
I think the convenience of the shortcut is trumped by multiple people wondering why their changes weren't applying when creating copies of their whole project folder, in which case the shortcut in the copied version will point to the lunar helper executable in the original project folder rather than the one in the copy, which is pretty confusing behavior.

**Comment by AmperSam-git** [comment]
yeah i've noticed this on my own things, i might just move LH to the top level folder possibly

**Comment by Underrout** [comment]
Actually, couldn't you also just make the shortcut use a relative path instead of an absolute one? I'd assume if that's supported it would also solve the problem. The only downside would be no longer being able to move the shortcut, but idk who'd be doing that anyway.
